### ISSUE TITLE
Please Close Channel

### ISSUE THREAD

**Issue by kheadings** [lightning-power-users/lightning-power-users-website#11]
We have a dangling channel that I cannot see on my side.  Can you see it on your side and can you close it?

channel ID:  037f3d5b948f9c048aa53f2818255d4e137aabf03255e6adf3bc347b82bd3d20f8

Thank you.
-Kevin
![Capture](https://user-images.githubusercontent.com/25985582/60920523-9b200e80-a255-11e9-8567-8857259cbf78.JPG)

**Comment by PierreRochard** [comment]
Hi @kheadings, that's the pubkey of your node, not the channel ID. 

You paid for this inbound capacity, are you sure you want me to close it?

**Comment by kheadings** [comment]
Hello Pierre,

I can't see the channel any longer and therefore don't know the channel
ID.  I'm ok with the BTC loss, this was just testing money.   If I can
clean this up, I'll try re-opening it.  Sorry for the hassle.

-Kevin

**Comment by PierreRochard** [comment]
No problem, just wanted to confirm, done.
