### ISSUE TITLE
Would you help me access my funds?

### ISSUE THREAD

**Issue by Relaxo143** [lightning-power-users/lightning-power-users-website#12]
Hello guys. I can't access this channel which I have opened with you (https://1ml.com/channel/637505638024937473) because I reinstalled Windows without backing up the node dir. I have the seed, but I dont think that will be enough for me the retrieve the funds once you force close the channel. Can you broadcast an early state and "steal" the sats on my side of the channel and then send them to me on or off chain? If you have any other ideas how we could achieve this I'm all ears. I use LND

**Comment by PierreRochard** [comment]
I wish I could, but I don't have any early states that can steal the sats on your side because the capacity started on your side. I'm sorry but those coins are gone :(

**Comment by Relaxo143** [comment]
> I wish I could, but I don't have any early states that can steal the sats on your side because the capacity started on your side. I'm sorry but those coins are gone :(

Oh yeah. Actually the earlier states have the balance on my side, not yours. Thank you for looking into it! That's a donation to all hodlers! 167 250 sats gone forever!

**Comment by PierreRochard** [comment]
Static channel backups to cloud will hopefully be ubiquitous soon!
