### ISSUE TITLE
2514 confirmations and channel still not closed closed

### ISSUE THREAD

**Issue by justin7942163** [lightning-power-users/lightning-power-users-website#14]
## Expected Behavior
Close channel and receive back unspent sats.

## Current Behavior
Channel was opened on the 27/09/2019, shortly after my LND went down due to hardware issues. I've since got my Lightning Node back up and my channel still hasn't been refunded for the 500,000 sats I committed to LightningPowerUsers, the channel is stuck in "closing"

## Possible Solution
Please send me back my 500,000 sats.

## Your Environment
Using LND on BTCPayServer and Zap Desktop

Transaction ID: https://blockstream.info/tx/5e1d9292acfc7230fbe948ca732c7e66ccaad73ad4bd5406a181c8367f5461c4

![image](https://user-images.githubusercontent.com/31229612/66742259-fe5bb580-eec2-11e9-9da5-bb85cdf0c287.png)

Please help me recover my funds.

**Comment by justin7942163** [comment]
Hey @PierreRochard I'm just bumping this thread, if you could please just force close the channel that's all I need to get my funds out of limbo.

**Comment by PierreRochard** [comment]
lncli closechannel --funding_txid 5e1d9292acfc7230fbe948ca732c7e66ccaad73ad4bd5406a181c8367f5461c4 --output_index 1 --force
{
	"closing_txid": "e88573e059b0e7f4781e8e6ea5854d4ba129606693df47e40379c5b7d9bdbca4"
}

sorry for the delay!

**Comment by justin7942163** [comment]
Thanks Pierre, got my funds back 👍
