### ISSUE TITLE
Inbound Capacity w/CASA

### ISSUE THREAD

**Issue by bitcoin21e8** [lightning-power-users/lightning-power-users-website#15]
Hi Lightning Power Users Team,

Used your website to obtain inbound capacity for my node. Went through the steps (connect, capacity, chain fee, payment) and paid via CASA lightning. Waited overnight and looked at my CASA node. I am not sure what my next step is because my inbound capacity is still showing ZERO. 

Am I connected to you? This is my lightning node IP.
03e843665ab212ce90ceb6a476fec5d9724013542f8ee1df52340c682c03a67db4@173.87.32.141:9735

**Comment by PierreRochard** [comment]
Hi! I do see that you paid for a channel, but for some reason the channel opening failed.

I tried manually opening a channel but can't connect, did you set up port forwarding? I'd recommend using Tor which is now available for Casa nodes

**Comment by bitcoin21e8** [comment]
Turned on Tor, thanks for the advice. 
03e843665ab212ce90ceb6a476fec5d9724013542f8ee1df52340c682c03a67db4@csyzskka2bnm6xhs2bcl3qnvbcshyg67wwjf6pvh7h7hfr7esrybw7id.onion:9735

Spent all morning learning about port forwarding. Had to put in a call to Frontier for access into my router’s IP. Long story short, I think I have this set up now.  
Will channel opening work now?

**Comment by bitcoin21e8** [comment]
I would pay for another channel opening but not sure if it would work. Thanks for your time Pierre.

**Comment by PierreRochard** [comment]
Keeping this open because it is an interesting problem, I tried connecting via Tor and got `[lncli] rpc error: code = Unknown desc = socks connect tcp 127.0.0.1:9050->csyzskka2bnm6xhs2bcl3qnbcshyg67wwjf6pvh7h7hfr7esrybw7id.onion:9735: unknown error TTL expired` as an error.


Could you please try buying a channel again, I'm happy to completely reimburse you because this is something I'd like to fix!

**Comment by bitcoin21e8** [comment]
Appreciate the dedication. I purchased a channel again.

**Comment by PierreRochard** [comment]
Ok, I've manually opened a channel, please post your a pay req here for a refund!

**Comment by bitcoin21e8** [comment]
Look at all that incoming liquidity, thank you. Humbled to be assisted by such a pioneer. Take my last payment as donation to keep kickin ass.
