### ISSUE TITLE
Paid you twice for incoming balance but channel still empty - resolution?

### ISSUE THREAD

**Issue by kaffeocash** [lightning-power-users/lightning-power-users-website#5]
## Expected Behavior
Pay according to the levels as advertised on lightningpowerusers.com and receive incoming balance in sats (250 000 in my case) on the channel which I had opened with 250 000 sats on my side.  

This is of course all in good fun, so I don't mind a small loss of my 9000 sats, but it would be good to know what went wrong, and possibly have it fixed!

## Current Behavior
I paid the fee, see screenshot below, for 1 hour setup time (9000 sats) but nothing happened. When checking after a few hours, the red message at the bottom of the screen showed up, indicating a time-out. 

Does this failure mean that the 9000 sats simly became a donation to you from me, or did they get lost in attempting to set up a transaction that will never go through?

I tried before with the cheapest version, but of course that didnt work either.  Today the transaction fees seem quite high. 

## Possible Solution
Try again manually to fund the channel between my node and yours. 

**My public key is:**
023a4c662ab9c71826b5793d3ab3853b993f0265f53ca7f648a562611176cf0b16@4kfc4zwkjjnbkn5a.onion:9735

<img width="1253" alt="Screenshot 2019-03-30 at 15 40 51" src="https://user-images.githubusercontent.com/30684361/55281844-43ab0200-533a-11e9-8344-80df7ae7f1ad.png">
<img width="1239" alt="Screenshot 2019-03-30 at 22 10 11" src="https://user-images.githubusercontent.com/30684361/55281848-4d346a00-533a-11e9-9bde-15d9faef704c.png">

## Steps to Reproduce (for bugs)

Pay 9000 sats to lightningpowerusers for inbound capacity after connecting your node and funding a channel with 250 000 sats. 

## Context
I would like more incoming funding of course to my open channels to help me spend and receive on the lightning network :)

## Your Environment
RaspiBlitz 1.1 

* Version used: current version of your website as of 2019-03-30
* Browser Name and version: Brave browser
* Operating System and version (desktop or mobile): desktop, MacOS Mojave, 10.14.3
* Link to your project: https://www.youtube.com/watch?v=edItjMHez48

**Comment by PierreRochard** [comment]
Sorry about that @kaffeocash! I just manually opened a channel. Looking at the logs, it looks like our websocket connection (which allows for real time updates) timed out. I'll dig into how to avoid that from happening. Thank you!

**Comment by kaffeocash** [comment]
Thank you @PierreRochard ! Working like a charm now, great to have your help in the bootstrapping of a new node! 👍
