### ISSUE TITLE
Inbound channel not showing

### ISSUE THREAD

**Issue by mpolavieja** [lightning-power-users/lightning-power-users-website#6]
I made a payment to open an inbound channel with you.  This is the tx id: c9dd4c76e772cdbb0b5e5e97a9b4fe236f8cb499e5e232ea1196458148be7732

But I am not seeing any inbound channel created in my node.  I am using a Casa node and my node id is the following: 03ca00a1f345ab6e1ed6a0756156ce1710861c6a61fcdd0bb62332c4e5e0685db1@81.36.30.35:9735

**Comment by PierreRochard** [comment]
Hello! I see both of our channels are active on my end. I'm not familiar with the Casa node as I don't own one. My recommendation would be to use the Node Launcher with Joule to have the best Lightning experience https://medium.com/lightning-power-users/windows-macos-lightning-network-284bd5034340

**Comment by PierreRochard** [comment]
I would recommend reaching out to Casa's paid support team
