### ISSUE TITLE
Inbound capacity

### ISSUE THREAD

**Issue by Prokorio** [lightning-power-users/lightning-power-users-website#7]
Hi,

I have requested a few days ago some inbound capacity on your website, unfortunately when I had to pay the invoice I have used my iOS wallet and not my node to pay it so I have got an error and never got any capacity (I guess)...

Would it be possible to have a refund?

This is the channel id https://1ml.com/channel/631485811871383553

and this my node 
https://1ml.com/node/03bd8e6a83933ce73fa74966b80920adc6010a1fdabea8577633088dbc5dee0662

Thank you

**Comment by PierreRochard** [comment]
Sorry about that @Prokorio! Please send me a payreq for 66,000 satoshis pierre@rochard.org
