### ISSUE TITLE
Opened LND channel on website / Inactive

### ISSUE THREAD

**Issue by StyriaTrading** [lightning-power-users/lightning-power-users-website#9]
I opened up successfully a channel today with you, but after it was confirmed it says the channel is inactive in my RTL interface. Is your node off? My LND pubkey is 029ff675e11523b84f4f057824c100d5a35321e483d26b6e5bfdfcc1ac71f58a84@193.83.127.102:9735

**Comment by PierreRochard** [comment]
Hi @StyriaTrading ! Thanks for opening a channel. My node is up and I see the channel as inactive oin my end as well. Have you tried restarting your node?

**Comment by Terpsy** [comment]
Hello @PierreRochard, 
 I also opened a channel 19h ago but the LightningPowerUsers.com node appears offline on my Joule. I have tried restarting my node successfully, but it still shows offline. My pubkey is 02d200b7ed4a915ab0e4689de22fe497b43e244ee79f0b2b7507597cb959668a80.

Thank you very much for all the great work you do.

**Comment by PierreRochard** [comment]
I see `"close_type": "FUNDING_CANCELED"` on my end, please try again
